# -*- coding: utf-8 -*-
# 28 строка - Цвета
# Form implementation generated from reading ui file 'RaPiMeIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import dbcon


class Ui_MainWindowLa(object):
    def setupUi(self, MainWindowLa, idd):
        MainWindowLa.setObjectName("MainWindowLa")
        MainWindowLa.setEnabled(True)
        MainWindowLa.resize(841, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindowLa)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 0, 800, 800))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(240, 100, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(0, 100, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(240, 180, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(0, 180, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(240, 260, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(0, 260, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")

        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(240, 340, 541, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(0, 340, 180, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setScaledContents(False)
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(674, 725, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 725, 131, 31))
        self.pushButton_3.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 800, 800))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        i1221=dbcon.q2("Лабораторноеисследование", "Элмедкарта", str(idd))
        i11=len(i1221)
        i3443 = dbcon.q2("Функцисследование", "Элмедкарта", str(idd))
        i22=len(i3443)
        xex = (i11 + i22)
        self.tableWidget.setRowCount(xex)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)


        for lu in range (xex):

            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(lu, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(lu, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(lu, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(lu, 3, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(lu, 4, item)

            if lu<i11 and dbcon.q("Врач", "Лабдиагностика", i1221[lu]) != '':

                brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                item.setBackground(brush)
            elif lu>=i11 and dbcon.q("Врач", "Функцдиагностика", i3443[lu-i11]) != '':

                brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                item.setBackground(brush)

            else:
                brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
                brush.setStyle(QtCore.Qt.SolidPattern)
                item.setBackground(brush)







        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setMinimumSectionSize(21)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 800, 800))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setRowCount(i22)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)


        for lu in range (i22):


            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(lu, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(lu, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(lu, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_2.setItem(lu, 3, item)



        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_2.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 800, 800))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setRowCount(i11)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)

        for lu in range(i11):

            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setItem(lu, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setItem(lu, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setItem(lu, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_3.setItem(lu, 3, item)






        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_3.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 800, 800))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_4.setFont(font)

        v11 = len(dbcon.q2("Вакцинация", "Элмедкарта", str(idd)))

        self.tableWidget_4.setRowCount(v11)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)


        for lu in range(v11):

            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(lu, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(lu, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(lu, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(lu, 3, item)








        self.tableWidget_4.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 800, 800))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_5.setFont(font)

        d11 = len(dbcon.q2("Резпосещврача", "Элмедкарта", str(idd)))


        self.tableWidget_5.setRowCount(d11)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)


        for lu in range(d11):

            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(lu, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(lu, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(lu, 2, item)






        self.tableWidget_5.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_5.horizontalHeader().setHighlightSections(True)
        self.tableWidget_5.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_5.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_5.verticalHeader().setVisible(False)
        self.tableWidget_5.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_5.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_5.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab, "")
        MainWindowLa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowLa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        self.menubar.setObjectName("menubar")
        MainWindowLa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowLa)
        self.statusbar.setObjectName("statusbar")
        MainWindowLa.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowLa, idd)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowLa)

    def retranslateUi(self, MainWindowLa, idd):
        _translate = QtCore.QCoreApplication.translate
        MainWindowLa.setWindowTitle(_translate("MainWindowLa", "MainWindowLa"))
        self.label_2.setText(_translate("MainWindowLa", "ФИО"))
        self.label_3.setText(_translate("MainWindowLa", dbcon.q('ФИО','Элмедкарта',str(idd))[1:len(dbcon.q('ФИО','Элмедкарта',str(idd)))-1]))
        self.label_4.setText(_translate("MainWindowLa", dbcon.q('Паспортныеданные','Элмедкарта',str(idd))[1:len(dbcon.q('Паспортныеданные','Элмедкарта',str(idd)))-1]))
        self.label_5.setText(_translate("MainWindowLa", "Паспорт. дан."))
        self.label_6.setText(_translate("MainWindowLa", dbcon.q('Номерполиса','Элмедкарта',str(idd))[1:len(dbcon.q('Номерполиса','Элмедкарта',str(idd)))-1]))
        self.label_7.setText(_translate("MainWindowLa", "Номер полиса"))
        self.label_8.setText(_translate("MainWindowLa", dbcon.q('ИНН','Элмедкарта',str(idd))))
        self.label_9.setText(_translate("MainWindowLa", "ИНН"))

        self.label_12.setText(_translate("MainWindowLa", dbcon.q('Датарождения','Элмедкарта',str(idd))))
        self.label_13.setText(_translate("MainWindowLa", "Дата рож."))
        self.pushButton.setText(_translate("MainWindow", "Записаться на прием"))
        self.pushButton_3.setText(_translate("MainWindow", "Отказаться от приема"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindowLa", "Общие данные"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowLa", "Тип"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowLa", "Название"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowLa", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowLa", "Врач"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowLa", "Готовность"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        i11=dbcon.q2("Лабораторноеисследование", "Элмедкарта", str(idd))
        i33=len(i11)
        i22=dbcon.q2("Функцисследование", "Элмедкарта", str(idd))
        xex = (i33 + len(i22))





        for lu in range(xex):

            if lu>i33-1:
                item = self.tableWidget.item(lu, 0)
                item.setText(_translate("MainWindowLa", "Функц иссл."))
                item = self.tableWidget.item(lu, 1)
                item.setText(_translate("MainWindowLa", dbcon.q("Названиеуслуги", "Функцдиагностика", str(i22[lu-i33]))))
                item = self.tableWidget.item(lu, 2)
                item.setText(_translate("MainWindowLa", dbcon.q("Датаисследования", "Функцдиагностика", str(i22[lu - i33]))))
                item = self.tableWidget.item(lu, 3)
                item.setText(_translate("MainWindowLa", dbcon.q("Врач", "Функцдиагностика", str(i22[lu - i33]))))
                item = self.tableWidget.item(lu, 4)
                if dbcon.q("Результат", "Функцдиагностика", str(i22[lu- i33]))=='None':
                    item.setText(_translate("MainWindowLa", '-'))
                else:

                    item.setText(_translate("MainWindowLa", '+'))
            else:
                item = self.tableWidget.item(lu, 0)
                item.setText(_translate("MainWindowLa", "Лаб иссл."))
                item = self.tableWidget.item(lu, 1)
                item.setText(_translate("MainWindowLa", dbcon.q("Названиеуслуги", "Лабдиагностика", str(i11[lu]))))
                item = self.tableWidget.item(lu, 2)
                item.setText(_translate("MainWindowLa", dbcon.q("Датаисследования", "Лабдиагностика", str(i11[lu]))))
                item = self.tableWidget.item(lu, 3)
                item.setText(_translate("MainWindowLa", dbcon.q("Врач", "Лабдиагностика", str(i11[lu]))))
                item = self.tableWidget.item(lu, 4)
                if dbcon.q("Результат", "Лабдиагностика", str(i11[lu]))=='None':
                    item.setText(_translate("MainWindowLa", '-'))
                else:
                    item.setText(_translate("MainWindowLa", '+'))








        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindowLa", "Направление"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowLa", "Название"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowLa", "Дата"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowLa", "Врач"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowLa", "Результат"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)


        for lu in range(len(i22)):


            item = self.tableWidget_2.item(lu, 0)
            item.setText(_translate("MainWindowLa", dbcon.q("Названиеуслуги", "Функцдиагностика", str(i22[lu]))))
            item = self.tableWidget_2.item(lu, 1)
            item.setText(_translate("MainWindowLa", dbcon.q("Датаисследования", "Функцдиагностика", str(i22[lu]))))
            item = self.tableWidget_2.item(lu, 2)
            item.setText(_translate("MainWindowLa", dbcon.q("Врач", "Функцдиагностика", str(i22[lu]))))
            item = self.tableWidget_2.item(lu, 3)
            if dbcon.q("Результат", "Функцдиагностика", str(i22[lu])) == 'None':
                item.setText(_translate("MainWindowLa", ''))
            else:
                item.setText(_translate("MainWindowLa", dbcon.q("Результат", "Функцдиагностика", str(i22[lu]))))




        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindowLa", "Дневник функц исследований"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowLa", "Название"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowLa", "Дата"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowLa", "Врач"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowLa", "Результат"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)

        for lu in range(i33):


            item = self.tableWidget_3.item(lu, 0)
            item.setText(_translate("MainWindowLa", dbcon.q("Названиеуслуги", "Лабдиагностика", str(i11[lu]))))
            item = self.tableWidget_3.item(lu, 1)
            item.setText(_translate("MainWindowLa", dbcon.q("Датаисследования", "Лабдиагностика", str(i11[lu]))))
            item = self.tableWidget_3.item(lu, 2)
            item.setText(_translate("MainWindowLa", dbcon.q("Врач", "Лабдиагностика", str(i11[lu]))))
            item = self.tableWidget_3.item(lu, 3)
            if dbcon.q("Результат", "Лабдиагностика", str(i11[lu])) == 'None':
                item.setText(_translate("MainWindowLa", ''))
            else:
                item.setText(_translate("MainWindowLa", dbcon.q("Результат", "Лабдиагностика", str(i11[lu]))))







        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6),
                                  _translate("MainWindowLa", "Дневник лаб исследований"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowLa", "Название"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowLa", "Тип вакцины"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowLa", "Дата начала"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowLa", "Дата конца "))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)

        v11 = (dbcon.q2("Вакцинация", "Элмедкарта", str(idd)))


        for lu in range(len(v11)):


            item = self.tableWidget_4.item(lu, 0)
            item.setText(_translate("MainWindowLa", dbcon.q("Название", "Прививочныйсертификат", str(v11[lu]))))
            item = self.tableWidget_4.item(lu, 1)
            item.setText(_translate("MainWindowLa", dbcon.q("Тип", "Прививочныйсертификат", str(v11[lu]))))
            item = self.tableWidget_4.item(lu, 2)
            item.setText(_translate("MainWindowLa", dbcon.q("Датапрививания", "Прививочныйсертификат", str(v11[lu]))))
            item = self.tableWidget_4.item(lu, 3)
            item.setText(_translate("MainWindowLa", dbcon.q("Датаокончания", "Прививочныйсертификат", str(v11[lu]))))



        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindowLa", "Дневник вакцинаций"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowLa", "Дата"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowLa", "Врач"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowLa", "Результат"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        d11 = (dbcon.q2("Резпосещврача", "Элмедкарта", str(idd)))

        for lu in range(len(d11)):


            item = self.tableWidget_5.item(lu, 0)
            item.setText(_translate("MainWindowLa", dbcon.q("Дата", "Результатыпосещенийврача", str(d11[lu]))))
            item = self.tableWidget_5.item(lu, 1)
            item.setText(_translate("MainWindowLa", dbcon.q("Врач", "Результатыпосещенийврача", str(d11[lu]))))
            item = self.tableWidget_5.item(lu, 2)
            item.setText(_translate("MainWindowLa", dbcon.q("Заключение", "Результатыпосещенийврача", str(d11[lu]))))




        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindowLa", "Диагнозы"))


