# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rama33.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRLA(object):
    def setupUi(self, MainWindowRLA):
        MainWindowRLA.setObjectName("MainWindowRLA")
        MainWindowRLA.resize(740, 825)
        MainWindowRLA.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindowRLA)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(265, 0, 165, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(27)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 740, 110, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 740, 153, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(13, 190, 720, 521))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        MainWindowRLA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowRLA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 21))
        self.menubar.setObjectName("menubar")
        MainWindowRLA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowRLA)
        self.statusbar.setObjectName("statusbar")
        MainWindowRLA.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowRLA)
        QtCore.QMetaObject.connectSlotsByName(MainWindowRLA)

    def retranslateUi(self, MainWindowRLA):
        _translate = QtCore.QCoreApplication.translate
        MainWindowRLA.setWindowTitle(_translate("MainWindowRLA", "MainWindowRLA"))
        self.label_3.setText(_translate("MainWindowRLA", "Результат"))
        self.pushButton.setText(_translate("MainWindowRLA", "Отменить"))
        self.pushButton_2.setText(_translate("MainWindowRLA", "Подтвердить"))
        self.textEdit.setHtml(_translate("MainWindowRLA", ""))



