# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YDALISSS.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowYDA(object):
    def setupUi(self, MainWindowYDA):
        MainWindowYDA.setObjectName("MainWindowYDA")
        MainWindowYDA.setEnabled(True)
        MainWindowYDA.resize(854, 800)
        MainWindowYDA.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindowYDA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(371, 30, 112, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setAcceptDrops(False)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 196, 161, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(152, 246, 151, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 720, 153, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 720, 110, 29))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindowYDA.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowYDA)
        self.statusbar.setObjectName("statusbar")
        MainWindowYDA.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowYDA)
        QtCore.QMetaObject.connectSlotsByName(MainWindowYDA)

    def retranslateUi(self, MainWindowYDA):
        _translate = QtCore.QCoreApplication.translate
        MainWindowYDA.setWindowTitle(_translate("MainWindowYDA", "MainWindowYDA"))
        self.label.setText(_translate("MainWindowYDA", "Запись"))
        self.label_2.setText(_translate("MainWindowYDA", "Тип"))
        self.comboBox.setItemText(0, _translate("MainWindowYDA", "Общий"))
        self.comboBox.setItemText(1, _translate("MainWindowYDA", "Функц"))
        self.comboBox.setItemText(2, _translate("MainWindowYDA", "Биохим"))
        self.comboBox.setItemText(3, _translate("MainWindowYDA", "Привив"))
        self.label_3.setText(_translate("MainWindowYDA", "№ Талона"))
        self.pushButton_2.setText(_translate("MainWindowYDA", "Подтвердить"))
        self.pushButton.setText(_translate("MainWindowYDA", "Назад"))



